# Generated by Django 3.0.6 on 2021-05-31 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal', models.TextField(max_length=255, verbose_name='Обращение')),
                ('room', models.CharField(max_length=15, verbose_name='Номер кабинета')),
                ('person', models.CharField(max_length=30, verbose_name='Отправитель')),
                ('status_done', models.BooleanField(default=False)),
                ('time_and_date', models.DateTimeField(auto_now_add=True, verbose_name='Время и дата регистрации задачи')),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарии об исполнении')),
                ('timedate_of_comment', models.DateTimeField(auto_now_add=True, verbose_name='Время завершения задачи')),
                ('name', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
